### PR TITLE
Add DateTimeOffset support to SlimSerializer

### PR DESCRIPTION
**Pull request by davidbrun**
Implement the native support of DateTimeOffset in SlimSerializer

### CODE REVIEW

**Comment by kalteherz** [comment]
@davidbrun 
As far as I know, there is the same problem with `IntPtr`.

**Review by kalteherz — APPROVED** [review]
LGTM

**Comment by itadapter** [comment]
@davidbrun 
Thanks for PR, we have it scheduled for review after another one today

**Comment by itadapter** [comment]
I reviewed the changes, look good to me.
I'd only add a unit test? @davidbrun

**Review by itadapter — COMMENTED** [review]
approved, merged

**Comment by zhabis** [comment]
All good. All tests passed. https://ci.appveyor.com/project/zhabis/azos/branch/master/tests
image

@davidbrun @kalteherz do you guys want a nuget for this ASAP? or do you wait for our next one (will be released in a day or two)

**Comment by kalteherz** [comment]
@zhabis 
I'm in no hurry. Still using modified NFX :)

@davidbrun @zhabis @itadapter 
Thanks for your work, nfx and azos projects 👍

**Comment by davidbrun** [comment]
@zhabis no immediate need on my side neither

**Pull request merged**
